LetWebApp/Models/SignInViewModel.cs
using System;

namespace LetWebApp.Models
{
    public class SignInViewModel
    {
        public string Email { get; set; }
        public string Sifra { get; set; }
    }
}

LetWebApp/Controllers/KorisnikController.cs
using BiznisLogika.Klase;
using Data.UnitOfWork;
using Domen;
using LetWebApp.Filteri;
using LetWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LetWebApp.Controllers
{
    [LoggedUserFillter]
    public class KorisnikController : Controller
    {
        private KorisnikServis servis;

        public KorisnikController()
        {
            servis = new KorisnikServis(new LetUnitOfWork(new LetContext()));
        }
        public IActionResult SignIn()
        {
            return View("Sign in");
        }
       public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateUser(Korisnik korisnik)
        {
            servis.Add(korisnik);
            return View(korisnik);
        }
    
       
        [HttpPost]
        public IActionResult SignIn(Korisnik korisnik)
        {
            try
            {
                Korisnik korisnik1 = servis.SignIn(korisnik);
                switch (korisnik1.TipKorisnika)
                {
                    case TipKorisnika.Administrator:
                        HttpContext.Session.SetInt32("tipKorisnika",0);

                        return RedirectToAction("ShowFlights", "Let");
                    case TipKorisnika.Agent:

                        HttpContext.Session.SetInt32("tipKorisnika",1);
                        return RedirectToAction("CreateFlight","Let");

                    case TipKorisnika.Posetilac:

                        HttpContext.Session.SetInt32("korisnikId",korisnik1.KorisnikId);
                        return RedirectToAction("Reservation","Rezervacija");
                    default:

                        return View();
                }
            }
            catch (Exception se)
            {

                ModelState.AddModelError(string.Empty, se.Message);
                return View("Sign in");
            }
          
        }
    }
}

LetWebApp/Controllers/LetController.cs
using BiznisLogika.Exceptions;
using BiznisLogika.Klase;
using Data.UnitOfWork;
using Domen;
using LetWebApp.Filteri;
using LetWebApp.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace LetWebApp.Controllers
{
    [LoggedUserFillter]
    public class LetController : Controller
    {

        private LetServis servis;
        private IHubContext<LetHub> context;
        public LetController(IHubContext<LetHub> context)
        {
            this.context = context;
            servis = new LetServis(new LetUnitOfWork(new LetContext()));
        }
        public IActionResult Index()
        {
            return View("Letovi",null);
        }
        public IActionResult ShowFlights()
        {
            var letovi = servis.GetAll();
            return View("Letovi",letovi);
        } 
        public IActionResult CreateFlight()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateFlight(Let let)
        {
            try
            {
                servis.Add(let);
            }
            catch (DestinationException )
            {
                let.LetId = -1;
            }
            catch (DateException )
            {
                let.LetId = -2;
            }

            return View(let);
        }
        [HttpGet]
        public List<Let> GetFlightsByCriteria(Mesto mestoPolaska,Mesto mestoDolaska)
        {
            var letovi = servis.GetByCondition(l => l.MestoPolaska == mestoPolaska && l.MestoDolaska == mestoDolaska
                                                && l.BrojMesta>0);

            return letovi;
        }

        [HttpDelete]
        public void DeleteFlight(int letId)
        {
            var let = servis.Find(l => l.LetId == letId);
            servis.Delete(let);

            context.Clients.All.SendAsync("deleteFlight", letId);
        }

    }
}

LetWebApp/Controllers/RezervacijaController.cs
using BiznisLogika.Exceptions;
using BiznisLogika.Klase;
using Data.UnitOfWork;
using Domen;
using LetWebApp.Hubs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LetWebApp.Controllers
{
    public class RezervacijaController : Controller
    {
        private IHubContext<LetHub> context;
        private RezervacijaServis servis;

        public RezervacijaController(IHubContext<LetHub> context)
        {
            this.context = context;
            servis = new RezervacijaServis(new LetUnitOfWork(new LetContext()));
        }
        public IActionResult Reservation()
        {
            return View();
        }
        public string FlightReserve(int id,int brojMesta)
        {
          int ?korisnikId =  HttpContext.Session.GetInt32("korisnikId");
            try
            {
                servis.CheckDate(id);
                Rezervacija rezervacija = new Rezervacija()
                {
                    KorisnikId = (int)korisnikId,
                    LetId = id,
                    StatusLeta = StatusLeta.NaCekanju,
                    BrojMesta = brojMesta
                };

                servis.Add(rezervacija);
                Rezervacija rez = servis.Find(r => r.KorisnikId == rezervacija.KorisnikId && r.LetId == rezervacija.LetId);

                var noviObjekat = new
                {
                    korisnikId = rez.KorisnikId,
                    letId = rez.LetId,
                    mestoDolaska = rez.Let.MestoDolaska.ToString(),
                    mestoPolaska = rez.Let.MestoPolaska.ToString(),
                    brojMesta = rez.BrojMesta,
                    datum = rez.Let.Datum.ToShortDateString(),
                    email = rez.Korisnik.Email
                };
                context.Clients.All.SendAsync("addNewReservation", noviObjekat);
                return null;
            }
            catch (DateException de)
            {
                return de.Message;
            }
            catch (ReservationException re)
            {
                return re.Message;
            }
            catch (Exception ex)
            {
                return $"Vec postoji rezervacija za ovog korisnika za dati let !";
            }
        }

        public IActionResult ShowReservation()
        {
            int ?korisnikId = HttpContext.Session.GetInt32("korisnikId");
            var rezervacije = servis.GetByCondition(r => r.KorisnikId == korisnikId);

            return View("UserReservations",rezervacije);
        }

      public IActionResult ShowAllReservation()
        {

            var rezervacije = servis.GetAll();
            return View("AllReservations", rezervacije);
        }
        [HttpPut]
       public void  AllowReservation(int letId,int korisnikId)
        {
            servis.ChangeStatus(letId, korisnikId);
            context.Clients.All.SendAsync("updateStatus",letId,korisnikId);
        }
    }
}

LetWebApp/Views/Korisnik/CreateUser.cshtml
@{
    Layout = "_LayoutAdministrator";
}
@model Korisnik

@if (!(Model is null))
{
    <script>alert("@Model.TipKorisnika" +" uspesno dodat");</script>
}
<form method="post" asp-controller="Korisnik" asp-action="CreateUser">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Email" name="Email" />
    </div>

    <div class="form-group">
        <input type="password" class="form-control" placeholder="Sifra" name="Sifra" />
    </div>

    <select name="TipKorisnika"
            id="tipKorisnika"
            class="form-control">
        <option value="Agent">Agent</option>
        <option value="Posetilac">Posetilac</option>
    </select>

    <div class="form-group" style="margin-top:20px">
        <input type="submit" class="btn btn-primary" value="Kreiraj korisnika" />
    </div>


</form>

LetWebApp/Views/Korisnik/Sign In.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="inner-container" style="width:50%">


        <h3>Log in</h3>
        <form method="post" asp-controller="Korisnik" asp-action="SignIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email " name="Email" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Your Password " name="Sifra" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Log in" />
            </div>

        </form>
    </div>
</div>

LetWebApp/Views/Let/CreateFlight.cshtml
@{
    Layout = "_LayoutAgent";
}
@model Let
             @if(Model!=null&& Model.LetId==-1)
            {
                <script>alert("Ne mozete imati isto mesto polaska i dolaska")</script>
             }
             else if(Model != null && Model.LetId == -2)
            {

                <script>alert("Datum ne moze biti u proslosti")</script>
            }
else if (Model!=null)
{
    <script>alert("Let uspesno dodat");</script>
}
<div class="d-flex p-2 justify-content-center ">
    <form method="post" asp-controller="Let" asp-action="CreateFlight">

        <div class="row">
            <div class="col">
                Pocetna destinacija:
                <select name="MestoPolaska"
                        id="mestoPolaska"
                        class="form-control">
                    <option value="Beograd">Beograd</option>
                    <option value="Nis">Nis</option>
                    <option value="Kraljevo">Kraljevo</option>
                    <option value="Pristina">Pristina</option>
                </select>
            </div>

            <div class="col">
                Kranja destinacija:
                <select name="MestoDolaska"
                        id="mestoDolaska"
                        class="form-control">
                    <option value="Beograd">Beograd</option>
                    <option value="Nis">Nis</option>
                    <option value="Kraljevo">Kraljevo</option>
                    <option value="Pristina">Pristina</option>
                </select>


            </div>
        </div>

        <div class="row">

            <div class="col">
                Broj presedanja:
                <input type="text" name="BrojPresedanja" class="form-control" required>

            </div>

            <div class="col">
                Broj mesta:
                <input type="text" name="BrojMesta" class="form-control" required>

            </div>
        </div>
        <div class="row">

            <div class="col">
                Datum leta:
                <input type="date" id="start" name="Datum"
                        required>
            </div>
        </div>

        <div class="row" style="margin-top:4px">
            <div class="col">
                <input type="submit" value="Kreiraj let" class="btn btn-success form-control">

            </div>
        </div>

    </form>
</div>

LetWebApp/Views/Let/Letovi.cshtml
@model List<Let>
@{
    if (ViewBag.TipKorisnika == 0)
        Layout = "_LayoutAdministrator";
    else
        Layout = "_LayoutAgent";

}

<h1>Letovi</h1>

<table style="border:1px solid black" id="" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Pocetna destinacija</th>
            <th>Krajnja destinacija</th>
            <th>Broj mesta</th>
            <th>Broj presedanja</th>
            <th>Datum</th>
            @if (ViewBag.TipKorisnika == 0)
            {
                <th>Deaktiviraj</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var let in Model)
        {
            if (let.BrojMesta < 5)
            {

                <tr style="background-color:yellow" id="@let.LetId">
                    <td>@let.MestoPolaska</td>
                    <td>@let.MestoDolaska</td>
                    <td>@let.BrojMesta</td>
                    <td>@let.BrojPresedanja</td>
                    <td>@let.Datum.ToShortDateString()</td>
                    @if (ViewBag.TipKorisnika == 0)
                    {
                        <td><span class="btn btn-link" id="@let.LetId" onclick="deleteFlight(this.id)">Otkazi let</span></td>
                    }
                </tr>

            }
            else
            {
                <tr id="@let.LetId">
                    <td>@let.MestoPolaska</td>
                    <td>@let.MestoDolaska</td>
                    <td>@let.BrojMesta</td>
                    <td>@let.BrojPresedanja</td>
                    <td>@let.Datum.Date.ToShortDateString()</td>
                    @if (ViewBag.TipKorisnika == 0)
                    {
                        <td><span class="btn btn-link" id="@let.LetId" onclick="deleteFlight(this.id)">Otkazi let</span></td>
                    }
                </tr>

            }
        }

    </tbody>
</table>

<script>

    function deleteFlight(id) {

        $.ajax({
            url: '@Url.ActionLink("DeleteFlight","Let")',
            data: {
                letId: id,

            },
            method: "delete",
            success: function (message) {

                alert("Izbrisan let");
            },
            error: function () {
                alert("Error!");
            }
        });
    }

</script>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/let.js"></script>

LetWebApp/Views/Rezervacija/AllReservations.cshtml
@{
    Layout = "_LayoutAgent";
}

@model List<Rezervacija>


<table style="border:1px solid black" id="" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Email korisnika</th>
            <th>Pocetna destinacija</th>
            <th>Krajnja destinacija</th>
            <th>Broj mesta</th>
            <th>Datum</th>
            <th>Odobri</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var let in Model)
        {
            <tr id="@let.LetId">
                <td>@let.Korisnik.Email</td>
                <td>@let.Let.MestoPolaska</td>
                <td>@let.Let.MestoDolaska</td>
                <td>@let.BrojMesta</td>
                <td>@let.Let.Datum.ToShortDateString()</td>
                <td><span class="btn btn-link" onclick="allowReservation(@let.LetId,@let.KorisnikId)">Odobri</span></td>

            </tr>

        }


    </tbody>
</table>

<script>
    function allowReservation(letId, korisnikId) {


        $.ajax({
            url: '@Url.ActionLink("AllowReservation","Rezervacija")',
            data: {
                letId: letId,
                korisnikId: korisnikId
            },
            method: "put",
            success: function (message) {

                alert("Odobrena rezervacija");


            },
            error: function () {
                alert("Error!");
            }
        });

        }

</script>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/let.js"></script>
<script src="~/js/rezervacije.js"></script>

LetWebApp/Views/Rezervacija/Reservation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    Layout = "_LayoutKorisnik";
}


<div class="container">

    <div class="row mb-5">
        <div class="col-lg-4">
            Pocetna destinacija:
            <select name="MestoPolaska"
                    id="mestoPolaska"
                    class="form-control">
                <option value="Mesto">Izaberite mesto</option>
                <option value="Beograd">Beograd</option>
                <option value="Nis">Nis</option>
                <option value="Kraljevo">Kraljevo</option>
                <option value="Pristina">Pristina</option>
            </select>
        </div>

        <div class="col-lg-4">
            Kranja destinacija:
            <select name="MestoDolaska"
                    id="mestoDolaska"
                    class="form-control">
                <option value="Mesto">Izaberite mesto</option>
                <option value="Beograd">Beograd</option>
                <option value="Nis">Nis</option>
                <option value="Kraljevo">Kraljevo</option>
                <option value="Pristina">Pristina</option>
            </select>


        </div>
        <div class="col-lg-4" >

            <div id="check" hidden="hidden" style="margin-top: 20px;margin-left: 55%">
                <input type="checkbox" id="vehicle1">
                <label for="vehicle1">Bez presedanja</label>
            </div>

        </div>
    </div>

    <div class="row">


        <div class="col">
            <table style="border:1px solid black" id="" class="table table-bordered table-striped">

                <thead>
                    <tr>
                        <th>Broj presedanja</th>
                        <th>Datum</th>
                        <th>Broj mesta</th>
                        <th>Rezervisi</th>

                    </tr>
                </thead>

                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <script>

    $('select').on('change', function (e) {

        $('#vehicle1').prop('checked', false);
        var polazak = document.getElementById("mestoPolaska");
        var dolazak = document.getElementById("mestoDolaska");

        var polazakVal = polazak.value;
        var dolazakVal = dolazak.value;

        if (polazakVal == 'Mesto' || dolazakVal == 'Mesto')
            return;

        if (polazakVal == dolazakVal) {
            alert("Ne moze isti polazak i dolazak !");
            return;
        }

      $.ajax({
          url: '@Url.ActionLink("GetFlightsByCriteria", "Let")',
          data: {
              mestoPolaska: polazakVal,
              mestoDolaska: dolazakVal
          },
            method: "get",
            success: function (data) {

                $("tbody tr").remove();
                for (var i = 0; i < data.length; i++) {

                    datum = new Date(data[i].datum).toLocaleDateString();
                    $("tbody").append("<tr id=" + data[i].letId + ">" +
                        "<td>" + data[i].brojPresedanja + "</td>" +
                        "<td>" + datum + "</td>" +
                        "<td><input type='text'/></td>" +
                        "<td>  <button onclick='reservation(this.id)' id="+data[i].letId+"> Rezervisi</button ></td>"+
                        + "</tr>");
                }
                $("#check").removeAttr("hidden");
            },
            error: function () {
                alert("Error!");
            }
        });



    });

    </script>

    <script>
    function reservation(id) {
        var row = $(`#${id}`).closest('tr');
        var brojMesta = row.find('td:eq(2)').children('input').val();
        alert(brojMesta);

        $.ajax({
            url: '@Url.ActionLink("FlightReserve","Rezervacija")',
            data: {
                id: id,
                brojMesta: brojMesta
            },
            method: "post",
            success: function (message) {
                if (message == null) {

                    alert("Uspesno rezervisan let");
                }
                else {
                    alert(message);

                }

            },
            error: function () {
                alert("Error!");
            }

        });
    }


    $("input[type=checkbox]").on("click", function (e) {
        var n = $("input:checked").length;
        if (n > 0) {
            bezPresedenja();
        }
        else {
            sviLetovi();
        }
    });

    function bezPresedenja() {
        $("tbody tr").each(function () {
            var row = $(this);
            var brojPresedanja = row.find('td:eq(0)').text();
            if (brojPresedanja > 0)
                row.attr("hidden", true);

        })

    }

    function sviLetovi() {
        $("tbody tr").each(function () {
            var row = $(this);

            row.removeAttr("hidden");
        })

    }
    </script>


    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/let.js"></script>

LetWebApp/Views/Rezervacija/UserReservations.cshtml
@{
    Layout = "_LayoutKorisnik";
}

@model List<Rezervacija>


<table style="border:1px solid black" id="" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Pocetna destinacija</th>
            <th>Krajnja destinacija</th>
            <th>Broj mesta</th>
            <th>Broj presedanja</th>
            <th>Datum</th>
            <th>Status</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var let in Model)
        {
           
            <tr id="@let.LetId">
                <td>@let.Let.MestoPolaska</td>
                <td>@let.Let.MestoDolaska</td>
                <td>@let.BrojMesta</td>
                <td>@let.Let.BrojPresedanja</td>
                <td>@let.Let.Datum.ToShortDateString()</td>
                <td id="@(let.LetId*10)@let.KorisnikId">@let.StatusLeta</td>

            </tr>

        }


    </tbody>
</table>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/let.js"></script>

LetWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LetWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LetWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LetWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LetWebApp/Views/Shared/_LayoutAdministrator.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LetWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Korisnik" asp-action="CreateUser">Unesi nove korisnike</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Let" asp-action="ShowFlights">Letovi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LetWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LetWebApp/Views/Shared/_LayoutAgent.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agent</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Let" asp-action="CreateFlight">Kreiraj let</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Let" asp-action="ShowFlights">Pregled letova</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rezervacija" asp-action="ShowAllReservation">Rezervacije</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LetWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>